# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true
org.gradle.dependencyVerification=off

# Mod Properties
mod_id=woot_revived
mod_name=Woot Revived
mod_version=20.4.1.10

# Platform Properties
java_version=17
mc_version=1.20.4
neo_version=20.4.239

# Dependency Properties
jei_version=17.3.1.4
jade_version=13.3.1
guideme_version=20.4.5
kubejs_version=2004.7.0-build.24

# KubeJS Dependencies
rhino_version=2004.2.3-build.4
architectury_version=11.1.17

# Optimization Mods
ferritecore_version=6.0.3-forge