# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true
org.gradle.dependencyVerification=off

# Mod Properties
mod_id=woot_revived
mod_name=Woot Revived
mod_version=21.1.1.11

# Platform Properties
java_version=21
mc_version=1.21.1
neo_version=21.1.199

# Dependency Properties
jei_version=19.25.0.322
jade_version=15.10.0+neoforge
guideme_version=21.1.9
kubejs_version=2101.7.2-build.270

# KubeJS Dependencies
rhino_version=2101.2.7-build.77

# Optimization Mods
ferritecore_version=7.0.2-neoforge