package wootrevived.woot.datagen.recipes;

import net.minecraft.data.recipes.*;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.Tags;
import wootrevived.woot.Woot;
import wootrevived.woot.datagen.Recipes;
import wootrevived.woot.registries.BlocksRegistry;
import wootrevived.woot.registries.FluidsRegistry;
import wootrevived.woot.registries.ItemsRegistry;
import wootrevived.woot.registries.UpgradeItemsRegistry;
import wootrevived.woot.upgrades.*;
import wootrevived.woot.upgrades.filter.Filter;

import java.util.function.Consumer;

public class Vanilla {
    public static void registerRecipes(Recipes recipes, Consumer<FinishedRecipe> consumer){
        /* Stygian Related */

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.STYGIAN_BLOCK.get())
                .pattern("aaa")
                .pattern("aaa")
                .pattern("aaa")
                .define('a', ItemsRegistry.STYGIAN_INGOT_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.STYGIAN_INGOT_ITEM.get()))
                .save(consumer);

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, ItemsRegistry.STYGIAN_INGOT_ITEM.get(), 9)
                .requires(BlocksRegistry.STYGIAN_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("0", recipes.hasItem(BlocksRegistry.STYGIAN_BLOCK.get()))
                .save(consumer, Woot.location("stygian_ingot_block"));

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, ItemsRegistry.STYGIAN_DUST_ITEM.get(), 2)
                .requires(Blocks.SOUL_SOIL)
                .requires(Tags.Items.GEMS_AMETHYST)
                .requires(Tags.Items.INGOTS_IRON)
                .requires(Items.FIRE_CHARGE)
                .group(Woot.MOD_ID)
                .unlockedBy("0", recipes.hasItem(Blocks.SOUL_SOIL))
                .unlockedBy("1", recipes.hasItem(Tags.Items.GEMS_AMETHYST))
                .unlockedBy("2", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("3", recipes.hasItem(Items.FIRE_CHARGE))
                .save(consumer);

        SimpleCookingRecipeBuilder.smelting(
                        Ingredient.of(ItemsRegistry.STYGIAN_DUST_ITEM.get()),
                        RecipeCategory.MISC,
                        ItemsRegistry.STYGIAN_INGOT_ITEM.get(),
                        1.0F, 200)
                .group(Woot.MOD_ID)
                .unlockedBy("0", recipes.hasItem(ItemsRegistry.STYGIAN_DUST_ITEM.get()))
                .save(consumer, Woot.location("stygian_ingot_cook"));

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, ItemsRegistry.STYGIAN_HAMMER_ITEM.get())
                .pattern(" ba")
                .pattern(" cb")
                .pattern("c  ")
                .define('a', BlocksRegistry.STYGIAN_BLOCK.get())
                .define('b', ItemsRegistry.STYGIAN_INGOT_ITEM.get())
                .define('c', Items.STICK)
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(BlocksRegistry.STYGIAN_BLOCK.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_INGOT_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(Items.STICK))
                .save(consumer);

        /* Xp Shard */

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, ItemsRegistry.XP_SHARD_ITEM.get())
                .pattern("aaa")
                .pattern("aaa")
                .pattern("aaa")
                .define('a', ItemsRegistry.XP_SPLINTER_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.XP_SPLINTER_ITEM.get()))
                .save(consumer);

        /* Anvil */

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.STYGIAN_ANVIL_BLOCK.get())
                .pattern("aaa")
                .pattern(" b ")
                .pattern("ccc")
                .define('a', BlocksRegistry.STYGIAN_BLOCK.get())
                .define('b', ItemsRegistry.STYGIAN_INGOT_ITEM.get())
                .define('c', Blocks.CRYING_OBSIDIAN)
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(BlocksRegistry.STYGIAN_BLOCK.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_INGOT_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(Blocks.CRYING_OBSIDIAN))
                .save(consumer);

        /* Magmator */

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.COPPER_MAGMATOR_BLOCK.get())
                .pattern("cbc")
                .pattern("bab")
                .pattern("cbc")
                .define('a', Blocks.MAGMA_BLOCK)
                .define('b', ItemsRegistry.STYGIAN_PLATE_ITEM.get())
                .define('c', ItemsRegistry.COPPER_SHARD_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Blocks.MAGMA_BLOCK))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(ItemsRegistry.COPPER_SHARD_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.IRON_MAGMATOR_BLOCK.get())
                .pattern("cbc")
                .pattern("bab")
                .pattern("cbc")
                .define('a', Blocks.MAGMA_BLOCK)
                .define('b', ItemsRegistry.STYGIAN_PLATE_ITEM.get())
                .define('c', ItemsRegistry.IRON_SHARD_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Blocks.MAGMA_BLOCK))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(ItemsRegistry.IRON_SHARD_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.GOLD_MAGMATOR_BLOCK.get())
                .pattern("cbc")
                .pattern("bab")
                .pattern("cbc")
                .define('a', Blocks.MAGMA_BLOCK)
                .define('b', ItemsRegistry.STYGIAN_PLATE_ITEM.get())
                .define('c', ItemsRegistry.GOLD_SHARD_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Blocks.MAGMA_BLOCK))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(ItemsRegistry.GOLD_SHARD_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.DIAMOND_MAGMATOR_BLOCK.get())
                .pattern("cbc")
                .pattern("bab")
                .pattern("cbc")
                .define('a', Blocks.MAGMA_BLOCK)
                .define('b', ItemsRegistry.STYGIAN_PLATE_ITEM.get())
                .define('c', ItemsRegistry.DIAMOND_SHARD_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Blocks.MAGMA_BLOCK))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(ItemsRegistry.DIAMOND_SHARD_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.NETHERITE_MAGMATOR_BLOCK.get())
                .pattern("cbc")
                .pattern("bab")
                .pattern("cbc")
                .define('a', Blocks.MAGMA_BLOCK)
                .define('b', ItemsRegistry.STYGIAN_PLATE_ITEM.get())
                .define('c', ItemsRegistry.NETHERITE_SHARD_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Blocks.MAGMA_BLOCK))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(ItemsRegistry.NETHERITE_SHARD_ITEM.get()))
                .save(consumer);

        /* Layout */

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.LAYOUT_BLOCK.get())
                .pattern(" b ")
                .pattern("bcb")
                .pattern(" a ")
                .define('a', ItemsRegistry.RED_DYE_PLATE_ITEM.get())
                .define('b', ItemsRegistry.LIGHT_BLUE_DYE_PLATE_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.RED_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.LIGHT_BLUE_DYE_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        /* Machines */

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.ITEM_INFUSER_BLOCK.get())
                .pattern(" a ")
                .pattern("cdc")
                .pattern(" b ")
                .define('a', Blocks.DROPPER)
                .define('b', Items.BUCKET)
                .define('c', Blocks.PISTON)
                .define('d', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Blocks.DROPPER))
                .unlockedBy("b", recipes.hasItem(Items.BUCKET))
                .unlockedBy("c", recipes.hasItem(Blocks.PISTON))
                .unlockedBy("d", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.FLUID_INFUSER_BLOCK.get())
                .pattern(" a ")
                .pattern("cdc")
                .pattern(" b ")
                .define('a', Blocks.BREWING_STAND)
                .define('b', Blocks.CAULDRON)
                .define('c', Items.BUCKET)
                .define('d', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Blocks.BREWING_STAND))
                .unlockedBy("b", recipes.hasItem(Blocks.CAULDRON))
                .unlockedBy("c", recipes.hasItem(Items.BUCKET))
                .unlockedBy("d", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.DYE_LIQUIFIER_BLOCK.get())
                .pattern("rgy")
                .pattern("lfm")
                .pattern("bnw")
                .define('r', Tags.Items.DYES_RED)
                .define('g', Tags.Items.DYES_GREEN)
                .define('y', Tags.Items.DYES_YELLOW)
                .define('l', Tags.Items.DYES_BLACK)
                .define('m', Tags.Items.DYES_MAGENTA)
                .define('b', Tags.Items.DYES_BLUE)
                .define('n', Tags.Items.DYES_BROWN)
                .define('w', Tags.Items.DYES_WHITE)
                .define('f', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("d", recipes.hasItem(Tags.Items.DYES))
                .unlockedBy("f", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.ENCHANTED_LIQUIFIER_BLOCK.get())
                .pattern("tpt")
                .pattern("tct")
                .pattern("tbt")
                .define('p', Blocks.PISTON)
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .define('b', Items.BUCKET)
                .define('t', Items.BOOK)
                .group(Woot.MOD_ID)
                .unlockedBy("p", recipes.hasItem(Blocks.PISTON))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .unlockedBy("b", recipes.hasItem(Items.BUCKET))
                .unlockedBy("t", recipes.hasItem(Items.BOOK))
                .save(consumer);

        /* Factory Blocks */

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', ItemsRegistry.STYGIAN_INGOT_ITEM.get())
                .define('b', ItemsRegistry.STYGIAN_PLATE_ITEM.get())
                .define('c', Blocks.CRYING_OBSIDIAN)
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.STYGIAN_INGOT_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(Blocks.CRYING_OBSIDIAN))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.COPPER_CELL_BLOCK.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', ItemsRegistry.ORANGE_DYE_PLATE_ITEM.get())
                .define('b', ItemsRegistry.COPPER_ENCHANTED_PLATE_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.ORANGE_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.COPPER_ENCHANTED_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.IRON_CELL_BLOCK.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', ItemsRegistry.WHITE_DYE_PLATE_ITEM.get())
                .define('b', ItemsRegistry.IRON_ENCHANTED_PLATE_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.WHITE_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.IRON_ENCHANTED_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.GOLD_CELL_BLOCK.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', ItemsRegistry.YELLOW_DYE_PLATE_ITEM.get())
                .define('b', ItemsRegistry.GOLD_ENCHANTED_PLATE_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.YELLOW_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.GOLD_ENCHANTED_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.DIAMOND_CELL_BLOCK.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', ItemsRegistry.LIGHT_BLUE_DYE_PLATE_ITEM.get())
                .define('b', ItemsRegistry.DIAMOND_ENCHANTED_PLATE_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.LIGHT_BLUE_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.DIAMOND_ENCHANTED_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.NETHERITE_CELL_BLOCK.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', ItemsRegistry.GRAY_DYE_PLATE_ITEM.get())
                .define('b', ItemsRegistry.NETHERITE_ENCHANTED_PLATE_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.GRAY_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.NETHERITE_ENCHANTED_PLATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.COPPER_PYLON_BLOCK.get())
                .pattern("aba")
                .pattern("aca")
                .pattern("aba")
                .define('a', Tags.Items.INGOTS_COPPER)
                .define('b', ItemsRegistry.COPPER_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_COPPER))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.COPPER_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.IRON_PYLON_BLOCK.get())
                .pattern("aba")
                .pattern("aca")
                .pattern("aba")
                .define('a', Tags.Items.INGOTS_IRON)
                .define('b', ItemsRegistry.IRON_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.IRON_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.GOLD_PYLON_BLOCK.get())
                .pattern("aba")
                .pattern("aca")
                .pattern("aba")
                .define('a', Tags.Items.INGOTS_GOLD)
                .define('b', ItemsRegistry.GOLD_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.GOLD_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.DIAMOND_PYLON_BLOCK.get())
                .pattern("aba")
                .pattern("aca")
                .pattern("aba")
                .define('a', Tags.Items.GEMS_DIAMOND)
                .define('b', ItemsRegistry.DIAMOND_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.DIAMOND_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.NETHERITE_PYLON_BLOCK.get())
                .pattern("aba")
                .pattern("aca")
                .pattern("aba")
                .define('a', Tags.Items.INGOTS_NETHERITE)
                .define('b', ItemsRegistry.NETHERITE_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.NETHERITE_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.COPPER_PLINTH_BLOCK.get())
                .pattern("aaa")
                .pattern("bcb")
                .pattern("aaa")
                .define('a', Tags.Items.INGOTS_COPPER)
                .define('b', ItemsRegistry.COPPER_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_COPPER))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.COPPER_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.IRON_PLINTH_BLOCK.get())
                .pattern("aaa")
                .pattern("bcb")
                .pattern("aaa")
                .define('a', Tags.Items.INGOTS_IRON)
                .define('b', ItemsRegistry.IRON_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.IRON_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.GOLD_PLINTH_BLOCK.get())
                .pattern("aaa")
                .pattern("bcb")
                .pattern("aaa")
                .define('a', Tags.Items.INGOTS_GOLD)
                .define('b', ItemsRegistry.GOLD_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.GOLD_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.DIAMOND_PLINTH_BLOCK.get())
                .pattern("aaa")
                .pattern("bcb")
                .pattern("aaa")
                .define('a', Tags.Items.GEMS_DIAMOND)
                .define('b', ItemsRegistry.DIAMOND_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.DIAMOND_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.NETHERITE_PLINTH_BLOCK.get())
                .pattern("aaa")
                .pattern("bcb")
                .pattern("aaa")
                .define('a', Tags.Items.INGOTS_NETHERITE)
                .define('b', ItemsRegistry.NETHERITE_SHARD_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.NETHERITE_SHARD_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.HEART_BLOCK.get())
                .pattern("cac")
                .pattern("aba")
                .pattern("cac")
                .define('a', ItemsRegistry.CYAN_DYE_PLATE_ITEM.get())
                .define('b', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .define('c', ItemsRegistry.BLUE_DYE_PLATE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.PURPLE_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .unlockedBy("c", recipes.hasItem(ItemsRegistry.PURPLE_DYE_PLATE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.FACTORY_CONNECT_BLOCK.get())
                .pattern("bab")
                .pattern("bcb")
                .pattern("bab")
                .define('a', Tags.Items.INGOTS_GOLD)
                .define('b', Tags.Items.DUSTS_REDSTONE)
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("b", recipes.hasItem(Tags.Items.DUSTS_REDSTONE))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.IMPORT_BLOCK.get())
                .pattern("bab")
                .pattern("bcb")
                .pattern("bab")
                .define('a', Items.HOPPER)
                .define('b', ItemsRegistry.STYGIAN_INGOT_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.HOPPER))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_INGOT_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.EXPORT_BLOCK.get())
                .pattern("bab")
                .pattern("bcb")
                .pattern("bab")
                .define('a', Items.CHEST)
                .define('b', ItemsRegistry.STYGIAN_INGOT_ITEM.get())
                .define('c', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.CHEST))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.STYGIAN_INGOT_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.FACTORY_CTR_BASE_PRI_BLOCK.get())
                .pattern("cdc")
                .pattern("aba")
                .pattern("cdc")
                .define('a', ItemsRegistry.RED_DYE_PLATE_ITEM.get())
                .define('b', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .define('c', FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get())
                .define('d', ItemsRegistry.PRISM_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.RED_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .unlockedBy("c", recipes.hasItem(FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get()))
                .unlockedBy("d", recipes.hasItem(ItemsRegistry.PRISM_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.FACTORY_CTR_BASE_SEC_BLOCK.get())
                .pattern("cdc")
                .pattern("aba")
                .pattern("cdc")
                .define('a', ItemsRegistry.LIGHT_BLUE_DYE_PLATE_ITEM.get())
                .define('b', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .define('c', FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get())
                .define('d', ItemsRegistry.PRISM_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.LIGHT_BLUE_DYE_PLATE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .unlockedBy("c", recipes.hasItem(FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get()))
                .unlockedBy("d", recipes.hasItem(ItemsRegistry.PRISM_ITEM.get()))
                .save(consumer);

        /* Upgrade Items */

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .pattern(" a ")
                .pattern("aba")
                .pattern(" a ")
                .define('a', ItemsRegistry.STYGIAN_INGOT_ITEM.get())
                .define('b', ItemsRegistry.BLACK_DYE_PLATE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.STYGIAN_INGOT_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(ItemsRegistry.BLACK_DYE_PLATE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, BlocksRegistry.FACTORY_UPGRADE_BLOCK.get())
                .pattern(" a ")
                .pattern("aba")
                .pattern(" a ")
                .define('a', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .define('b', BlocksRegistry.FACTORY_BASE_BLOCK.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(BlocksRegistry.FACTORY_BASE_BLOCK.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Decapitate.COPPER_DECAPITATE_ITEM.get())
                .pattern("cac")
                .pattern("aba")
                .pattern("cac")
                .define('a', Items.ZOMBIE_HEAD)
                .define('b', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .define('c', Tags.Items.INGOTS_COPPER)
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.ZOMBIE_HEAD))
                .unlockedBy("b", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(Tags.Items.INGOTS_COPPER))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Decapitate.IRON_DECAPITATE_ITEM.get())
                .pattern("cac")
                .pattern("aba")
                .pattern("cac")
                .define('a', Items.SKELETON_SKULL)
                .define('b', Decapitate.COPPER_DECAPITATE_ITEM.get())
                .define('c', Tags.Items.INGOTS_IRON)
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.ZOMBIE_HEAD))
                .unlockedBy("b", recipes.hasItem(Decapitate.COPPER_DECAPITATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Decapitate.GOLD_DECAPITATE_ITEM.get())
                .pattern("cac")
                .pattern("aba")
                .pattern("cac")
                .define('a', Items.CREEPER_HEAD)
                .define('b', Decapitate.IRON_DECAPITATE_ITEM.get())
                .define('c', Tags.Items.INGOTS_GOLD)
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.CREEPER_HEAD))
                .unlockedBy("b", recipes.hasItem(Decapitate.IRON_DECAPITATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Decapitate.DIAMOND_DECAPITATE_ITEM.get())
                .pattern("cac")
                .pattern("aba")
                .pattern("cac")
                .define('a', Items.WITHER_SKELETON_SKULL)
                .define('b', Decapitate.GOLD_DECAPITATE_ITEM.get())
                .define('c', Tags.Items.GEMS_DIAMOND)
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.WITHER_SKELETON_SKULL))
                .unlockedBy("b", recipes.hasItem(Decapitate.GOLD_DECAPITATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Decapitate.NETHERITE_DECAPITATE_ITEM.get())
                .pattern("cac")
                .pattern("aba")
                .pattern("cac")
                .define('a', Items.DRAGON_HEAD)
                .define('b', Decapitate.DIAMOND_DECAPITATE_ITEM.get())
                .define('c', Tags.Items.INGOTS_NETHERITE)
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.DRAGON_HEAD))
                .unlockedBy("b", recipes.hasItem(Decapitate.DIAMOND_DECAPITATE_ITEM.get()))
                .unlockedBy("c", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Efficiency.COPPER_EFFICIENCY_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get())
                .define('b', Tags.Items.INGOTS_COPPER)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_COPPER))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Efficiency.IRON_EFFICIENCY_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get())
                .define('b', Tags.Items.INGOTS_IRON)
                .define('c', Efficiency.COPPER_EFFICIENCY_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("c", recipes.hasItem(Efficiency.COPPER_EFFICIENCY_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Efficiency.GOLD_EFFICIENCY_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get())
                .define('b', Tags.Items.INGOTS_GOLD)
                .define('c', Efficiency.IRON_EFFICIENCY_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("c", recipes.hasItem(Efficiency.IRON_EFFICIENCY_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Efficiency.DIAMOND_EFFICIENCY_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get())
                .define('b', Tags.Items.GEMS_DIAMOND)
                .define('c', Efficiency.GOLD_EFFICIENCY_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .unlockedBy("c", recipes.hasItem(Efficiency.GOLD_EFFICIENCY_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Efficiency.NETHERITE_EFFICIENCY_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get())
                .define('b', Tags.Items.INGOTS_NETHERITE)
                .define('c', Efficiency.DIAMOND_EFFICIENCY_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(FluidsRegistry.VITALITY_FUEL_FLUID_BUCKET.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .unlockedBy("c", recipes.hasItem(Efficiency.DIAMOND_EFFICIENCY_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Looting.COPPER_LOOTING_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Tags.Items.INGOTS_COPPER)
                .define('b', Items.STICK)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_COPPER))
                .unlockedBy("b", recipes.hasItem(Items.STICK))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Looting.IRON_LOOTING_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Tags.Items.INGOTS_IRON)
                .define('b', Items.STICK)
                .define('c', Looting.COPPER_LOOTING_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("b", recipes.hasItem(Items.STICK))
                .unlockedBy("c", recipes.hasItem(Looting.COPPER_LOOTING_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Looting.GOLD_LOOTING_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Tags.Items.INGOTS_GOLD)
                .define('b', Items.STICK)
                .define('c', Looting.IRON_LOOTING_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("b", recipes.hasItem(Items.STICK))
                .unlockedBy("c", recipes.hasItem(Looting.IRON_LOOTING_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Looting.DIAMOND_LOOTING_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Tags.Items.GEMS_DIAMOND)
                .define('b', Items.STICK)
                .define('c', Looting.GOLD_LOOTING_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .unlockedBy("b", recipes.hasItem(Items.STICK))
                .unlockedBy("c", recipes.hasItem(Looting.GOLD_LOOTING_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Looting.NETHERITE_LOOTING_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Tags.Items.INGOTS_NETHERITE)
                .define('b', Items.STICK)
                .define('c', Looting.DIAMOND_LOOTING_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .unlockedBy("b", recipes.hasItem(Items.STICK))
                .unlockedBy("c", recipes.hasItem(Looting.DIAMOND_LOOTING_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Mass.COPPER_MASS_ITEM.get())
                .pattern("aaa")
                .pattern("aba")
                .pattern("aaa")
                .define('a', Tags.Items.INGOTS_COPPER)
                .define('b', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_COPPER))
                .unlockedBy("b", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Mass.IRON_MASS_ITEM.get())
                .pattern("aaa")
                .pattern("aba")
                .pattern("aaa")
                .define('a', Tags.Items.INGOTS_IRON)
                .define('b', Mass.COPPER_MASS_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("b", recipes.hasItem(Mass.COPPER_MASS_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Mass.GOLD_MASS_ITEM.get())
                .pattern("aaa")
                .pattern("aba")
                .pattern("aaa")
                .define('a', Tags.Items.INGOTS_GOLD)
                .define('b', Mass.IRON_MASS_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("b", recipes.hasItem(Mass.IRON_MASS_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Mass.DIAMOND_MASS_ITEM.get())
                .pattern("aaa")
                .pattern("aba")
                .pattern("aaa")
                .define('a', Tags.Items.GEMS_DIAMOND)
                .define('b', Mass.GOLD_MASS_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .unlockedBy("b", recipes.hasItem(Mass.GOLD_MASS_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Mass.NETHERITE_MASS_ITEM.get())
                .pattern("aaa")
                .pattern("aba")
                .pattern("aaa")
                .define('a', Tags.Items.INGOTS_NETHERITE)
                .define('b', Mass.DIAMOND_MASS_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .unlockedBy("b", recipes.hasItem(Mass.DIAMOND_MASS_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Rate.COPPER_RATE_ITEM.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', Tags.Items.INGOTS_COPPER)
                .define('b', Tags.Items.DUSTS_REDSTONE)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_COPPER))
                .unlockedBy("b", recipes.hasItem(Tags.Items.DUSTS_REDSTONE))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Rate.IRON_RATE_ITEM.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', Tags.Items.INGOTS_IRON)
                .define('b', Tags.Items.DUSTS_REDSTONE)
                .define('c', Rate.COPPER_RATE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("b", recipes.hasItem(Tags.Items.DUSTS_REDSTONE))
                .unlockedBy("c", recipes.hasItem(Rate.COPPER_RATE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Rate.GOLD_RATE_ITEM.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', Tags.Items.INGOTS_GOLD)
                .define('b', Tags.Items.DUSTS_REDSTONE)
                .define('c', Rate.IRON_RATE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("b", recipes.hasItem(Tags.Items.DUSTS_REDSTONE))
                .unlockedBy("c", recipes.hasItem(Rate.IRON_RATE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Rate.DIAMOND_RATE_ITEM.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', Tags.Items.GEMS_DIAMOND)
                .define('b', Tags.Items.DUSTS_REDSTONE)
                .define('c', Rate.GOLD_RATE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .unlockedBy("b", recipes.hasItem(Tags.Items.DUSTS_REDSTONE))
                .unlockedBy("c", recipes.hasItem(Rate.GOLD_RATE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Rate.NETHERITE_RATE_ITEM.get())
                .pattern("aba")
                .pattern("bcb")
                .pattern("aba")
                .define('a', Tags.Items.INGOTS_NETHERITE)
                .define('b', Tags.Items.DUSTS_REDSTONE)
                .define('c', Rate.DIAMOND_RATE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .unlockedBy("b", recipes.hasItem(Tags.Items.DUSTS_REDSTONE))
                .unlockedBy("c", recipes.hasItem(Rate.DIAMOND_RATE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, ShardDrop.IRON_SHARD_DROP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', ItemsRegistry.COPPER_SHARD_ITEM.get())
                .define('b', Tags.Items.INGOTS_IRON)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.COPPER_SHARD_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, ShardDrop.GOLD_SHARD_DROP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', ItemsRegistry.IRON_SHARD_ITEM.get())
                .define('b', Tags.Items.INGOTS_GOLD)
                .define('c', ShardDrop.IRON_SHARD_DROP_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.IRON_SHARD_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("c", recipes.hasItem(ShardDrop.IRON_SHARD_DROP_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, ShardDrop.DIAMOND_SHARD_DROP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', ItemsRegistry.GOLD_SHARD_ITEM.get())
                .define('b', Tags.Items.GEMS_DIAMOND)
                .define('c', ShardDrop.GOLD_SHARD_DROP_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.GOLD_SHARD_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .unlockedBy("c", recipes.hasItem(ShardDrop.GOLD_SHARD_DROP_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, ShardDrop.NETHERITE_SHARD_DROP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', ItemsRegistry.DIAMOND_SHARD_ITEM.get())
                .define('b', Tags.Items.INGOTS_NETHERITE)
                .define('c', ShardDrop.DIAMOND_SHARD_DROP_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(ItemsRegistry.DIAMOND_SHARD_ITEM.get()))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .unlockedBy("c", recipes.hasItem(ShardDrop.DIAMOND_SHARD_DROP_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Xp.COPPER_XP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.EXPERIENCE_BOTTLE)
                .define('b', Tags.Items.INGOTS_COPPER)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.EXPERIENCE_BOTTLE))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_COPPER))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Xp.IRON_XP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.EXPERIENCE_BOTTLE)
                .define('b', Tags.Items.INGOTS_IRON)
                .define('c', Xp.COPPER_XP_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.EXPERIENCE_BOTTLE))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_IRON))
                .unlockedBy("c", recipes.hasItem(Xp.COPPER_XP_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Xp.GOLD_XP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.EXPERIENCE_BOTTLE)
                .define('b', Tags.Items.INGOTS_GOLD)
                .define('c', Xp.IRON_XP_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.EXPERIENCE_BOTTLE))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_GOLD))
                .unlockedBy("c", recipes.hasItem(Xp.IRON_XP_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Xp.DIAMOND_XP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.EXPERIENCE_BOTTLE)
                .define('b', Tags.Items.GEMS_DIAMOND)
                .define('c', Xp.GOLD_XP_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.EXPERIENCE_BOTTLE))
                .unlockedBy("b", recipes.hasItem(Tags.Items.GEMS_DIAMOND))
                .unlockedBy("c", recipes.hasItem(Xp.GOLD_XP_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Xp.NETHERITE_XP_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.EXPERIENCE_BOTTLE)
                .define('b', Tags.Items.INGOTS_NETHERITE)
                .define('c', Xp.DIAMOND_XP_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.EXPERIENCE_BOTTLE))
                .unlockedBy("b", recipes.hasItem(Tags.Items.INGOTS_NETHERITE))
                .unlockedBy("c", recipes.hasItem(Xp.DIAMOND_XP_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Burn.BURN_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.FIRE_CHARGE)
                .define('b', Items.LAVA_BUCKET)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.FIRE_CHARGE))
                .unlockedBy("b", recipes.hasItem(Items.LAVA_BUCKET))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Filter.FILTER_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.HOPPER)
                .define('b', Items.COMPARATOR)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.HOPPER))
                .unlockedBy("b", recipes.hasItem(Items.COMPARATOR))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Dimension.NETHER_DIMENSION_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.GHAST_TEAR)
                .define('b', Items.BLAZE_ROD)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.GHAST_TEAR))
                .unlockedBy("b", recipes.hasItem(Items.BLAZE_ROD))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, Dimension.END_DIMENSION_ITEM.get())
                .pattern("bab")
                .pattern("aca")
                .pattern("bab")
                .define('a', Items.CHORUS_FRUIT)
                .define('b', Items.SHULKER_SHELL)
                .define('c', UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("a", recipes.hasItem(Items.CHORUS_FRUIT))
                .unlockedBy("b", recipes.hasItem(Items.SHULKER_SHELL))
                .unlockedBy("c", recipes.hasItem(UpgradeItemsRegistry.UPGRADE_BASE_ITEM.get()))
                .save(consumer);

        /* Guide Book */

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, ItemsRegistry.GUIDE_BOOK_ITEM.get())
                .requires(Items.BOOK)
                .requires(ItemsRegistry.STYGIAN_INGOT_ITEM.get())
                .group(Woot.MOD_ID)
                .unlockedBy("0", recipes.hasItem(Items.BOOK))
                .unlockedBy("1", recipes.hasItem(ItemsRegistry.STYGIAN_INGOT_ITEM.get()))
                .save(consumer);
    }
}
